### ISSUE TITLE
solution.ipynb - is not rendered

### ISSUE THREAD

**Issue by Olgerd96** [alukyantsev/dataworkshop#1]
не могу посмотреть solution.ipynb - пишет что слишком долго его рендерит - поэтому не покажу...
может есть какой то способ отобразить на гитхабе не скачивая себе?

**Comment by alukyantsev** [comment]
Уменьшил размер файла блокнота, теперь открывается на github.

Также сделал ссылки на Google Colab, если вдруг там смотреть удобнее:
solution - https://colab.research.google.com/drive/1FVlIlwXlldH93ok4iEytcuqri3Odlq2C
solution-fix - https://colab.research.google.com/drive/10uor48GGnTFSjt1FiVPO65BbIP2Y89Jt

**Comment by Olgerd96** [comment]
чтобы удобнее было найти решение - попробую добавить в описание, а вопрос с тем что ноутбук не открывался - решен полностью. только я не понял как удалось картинки отделить от ноутбука, но вопрос же был не в этом...

**Comment by alukyantsev** [comment]
Картинки кладутся отдельно в папку и в блокноте ставится ссылка на них.
